---
# Install NGINX
    - name: Install nginx
      package:
        name: nginx
        state: present
      become: true
      become_user: root
      tag: nginx

    - name: Check nginx service is running
      service:
        name: nginx
        enabled: yes
        state: started
      tag: nginx
